#!/bin/sh

urlregex="(((http|https)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

# First remove linebreaks and mutt sidebars:
urls="$(sed 's/.*│//g' | tr -d '\n' |
	grep -aEo "$urlregex" | # grep only urls as defined above.
	uniq | # Ignore neighboring duplicates.
	sed 's/^www./http:\/\/www\./g')"

[ -z "$urls" ] && exit

# use gruvbox theme for dmenu (see dwm/config.h)
normbgcolor="#282828"
normfgcolor="#ebdbb2"
selfgcolor="#282828"
selbgcolor="#d79921"

chosen="$(echo "$urls" | dmenu -i -p 'Follow which url?' -l 10 -w ${WINDOWID} -nb ${normbgcolor} -nf ${normfgcolor} -sb ${selbgcolor} -sf ${selfgcolor})"

setsid xdg-open "$chosen" >/dev/null 2>&1 &